image: Visual Studio 2017

version: 0.0.0.{build}
skip_branch_with_pr: true

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  Harpoon_Connection_String: "Server=(local)\\SQL2017;Database=TEST_HARPOON_{0};User ID=sa;Password=Password12!;Trusted_Connection=True;MultipleActiveResultSets=true"
  matrix: 
    - IS_TAG: true
    - IS_TAG: false

configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj, appveyor.yml'
  - '%LocalAppData%\NuGet\v3-cache -> **\*.csproj, appveyor.yml'

services:
  - mssql2017

install:
- choco install opencover.portable
- choco install codecov

for:
-
  matrix:
    only:
      - IS_TAG: false

  skip_tags: true
-
  matrix:
    only:
      - IS_TAG: true

  skip_non_tags: true

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: $env:APPVEYOR_REPO_TAG_NAME 
    package_version: $env:APPVEYOR_REPO_TAG_NAME
    assembly_version: $env:APPVEYOR_REPO_TAG_NAME
    file_version: $env:APPVEYOR_REPO_TAG_NAME
    informational_version: $env:APPVEYOR_REPO_TAG_NAME

  build:
    publish_nuget: true
    publish_nuget_symbols: true 

  deploy:
  - provider: NuGet
    api_key:
      secure: ZgE98SOlPZYmk0o6FDdf3qQd2oij9awTlKcpsyMyuO8jz0x6zmBBcFaiYjsSlnSR

before_build:
- dotnet restore

build:
  verbosity: minimal

test_script:
- OpenCover.Console.exe -returntargetcode -oldstyle -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test  /p:DebugType=full -c Debug Harpoon.sln" -filter:"+[Harpoon*]* -[*Tests*]*" -output:Harpoon_coverage.xml
- codecov -f Harpoon_coverage.xml