image: Visual Studio 2019

version: 0.0.0.{build}
skip_branch_with_pr: true

environment:
  rabbitmq_installer_path: "C:\\Users\\appveyor\\rabbitmq-server-3.7.6.exe"
  rabbitmq_installer_download_url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.6/rabbitmq-server-3.7.6.exe"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  Harpoon_Connection_String: "Server=(local)\\SQL2017;Database=TEST_HARPOON_{0};User ID=sa;Password=Password12!;Trusted_Connection=True;MultipleActiveResultSets=true"
  matrix: 
    - IS_TAG: true
    - IS_TAG: false

configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - '%LocalAppData%\NuGet\v3-cache -> **\*.csproj'
  - '%rabbitmq_installer_path% -> appveyor.yml'

services:
  - mssql2017

install:
- choco install opencover.portable codecov

for:
-
  matrix:
    only:
      - IS_TAG: false

  skip_tags: true
-
  matrix:
    only:
      - IS_TAG: true

  skip_non_tags: true

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: $(appveyor_repo_tag_name)
    package_version: $(appveyor_repo_tag_name)
    assembly_version: $(appveyor_repo_tag_name)
    file_version: $(appveyor_repo_tag_name)
    informational_version: $(appveyor_repo_tag_name)

  build:
    publish_nuget: true
    publish_nuget_symbols: true 

  deploy:
  - provider: NuGet
    api_key:
      secure: RQvz2NHd2oqyiItbxLeZtsyCgM46T1CN4KwKyomsQ42tObHAM7T2McW6WbED/ICJ

before_build:
- dotnet restore

build:
  verbosity: minimal

before_test:
- ps: if (-Not (Test-Path "$env:rabbitmq_installer_path")) { (New-Object Net.WebClient).DownloadFile("$env:rabbitmq_installer_download_url", "$env:rabbitmq_installer_path") } else { Write-Host "Found" $env:rabbitmq_installer_path "in cache." }
- start /B /WAIT %rabbitmq_installer_path% /S
- ps: $rabbitPath = 'C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.6'
- ps: Start-Process -Wait "$rabbitPath\sbin\rabbitmq-service.bat" "install"
- ps: Start-Process -Wait "$rabbitPath\sbin\rabbitmq-service.bat" "start"

test_script:
- OpenCover.Console.exe -returntargetcode -oldstyle -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test  /p:DebugType=full -c Debug Harpoon.sln" -filter:"+[Harpoon*]* -[*Tests*]*" -output:Harpoon_coverage.xml
- codecov -f Harpoon_coverage.xml