image: Visual Studio 2019

version: 2.0.{build}

environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  only:
    - master

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

configuration: Release
platform: Any CPU

install:
- choco install dotnetcore-sdk --version 2.2.105
- choco install opencover.portable
- choco install codecov

before_build:
- dotnet restore

build:
  project: Harpoon.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Harpoon.Tests\bin\Release\netcoreapp2.2\Harpoon.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\Harpoon_coverage.xml"
- codecov -f "Harpoon_coverage.xml"