using System;

namespace Harpoon
{
    /// <summary>
    /// Unique work item generated by a <see cref="IWebHookNotification"/>
    /// </summary>
    public class WebHookWorkItem : IWebHookWorkItem
    {
        /// <inheritdoc />
        public Guid Id { get; }
        /// <inheritdoc />
        public DateTime Timestamp { get; }
        /// <inheritdoc />
        public IWebHookNotification Notification { get; }
        /// <inheritdoc />
        public IWebHook WebHook { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebHookWorkItem"/> class.
        /// </summary>
        public WebHookWorkItem(Guid id, IWebHookNotification notification, IWebHook webHook)
        {
            Notification = notification ?? throw new ArgumentNullException(nameof(notification));
            WebHook = webHook ?? throw new ArgumentNullException(nameof(webHook));
            Timestamp = DateTime.UtcNow;
            Id = id;
        }
    }
}